### ISSUE TITLE
Warning Popup "No internet connection detected"

### ISSUE THREAD

**Issue by Ojayyy** [wrld3d/unity-api#115]
### Description

Unnecessary Warning Message "No internet connection detected"

![image](https://user-images.githubusercontent.com/13174622/141818925-604a6f48-95dd-4973-b340-295f09dc9dbf.png)

### Steps to Reproduce

Just after running the Unity editor using the WrldMap Script the message pops up. After I have acknowledged the message, everything works well

Any advice to get rid of this message?

### Additional Information

Unity 2020.3.22f1 (LTS)
WRLD Unity SDK v0.8.17

**Comment by steve-curtis** [comment]
Hi - ﻿We have recently become aware of an issue which affects the WRLD Android SDK and the WRLD Unity SDK when building for Android devices. Users of your app will see a popup "No internet connection detected. Some functionality may be disabled" when the app starts, and may also experience issues entering indoor maps.

﻿WRLD Javascript, iOS and Unity apps on non-Android devices are not affected by the issue.

﻿The issue has now been resolved in the latest versions of the WRLD SDK, but you will need to update and rebuild your apps. The fix is available in the following SDK versions:

﻿* WRLD Android SDK - v0.0.1376 - available from Maven https://search.maven.org/artifact/com.wrld3d/wrld-android-sdk/0.0.1376/aar - update the dependency in your build.gradle file to com.wrld3d:wrld-android-sdk:0.0.1376@aar

﻿* WRLD Unity SDK v0.8.103 - download from https://cdn1.wrld3d.com/unity/wrld.unity.sdk.0.8.103.release.zip and import into your Unity project

﻿
﻿Apologies for the inconvenience caused to you and your users by this issue. If you have any further questions or concerns, please contact us by replying to this email or contacting our support chat service at www.wrld3d.com

**Comment by Ojayyy** [comment]
WRLD Unity SDK v0.8.103 solved it! Thx!
