### ISSUE TITLE
Using non-streamed detail in Unity games

### ISSUE THREAD

**Issue by kennyrogers40** [wrld3d/unity-api#21]
Where can I find out how to pre-load my Unity game with WRLD details (I don't want my users having to rely on streaming).  

Am I able to select a reduced level of detail, for sake of game performance?

**Comment by tim-jenks** [comment]
@kennyrogers40 it is not currently possible to pre-load WRLD assets in Unity, this is something we are considering adding in the future.

You are not currently able to change the LOD, again this is something we are considering adding in the future.

**Comment by mehmetokalkan** [comment]
Hi, I wonder the same thing. Your maps are really cool but I want to replace them with realistic building with high resolution texture but as I understand it is not possible right now. Your maps are not editable right now, right?

**Comment by GabrielBakker** [comment]
That is a completely different question then what kennyrogers was asking.

Kenny wants to load the maps in his unity project so that his games don't
require internet to work, and so they run faster in the beginning.

You are trying to edit the maps and building textures, which i believe is
totally possible, but thats not a unity question, thats a map editing
question.

Unless you ARE trying to do it in Unity, in which case, stream their map
with no buildings, and put the buildings in yourself wherever you want
using Unity!

Gabriel

**Comment by mehmetokalkan** [comment]
Ah sorry I didn't mention that, I downloaded/used the Unity project. Well basically I love the real world scale and thing that you are using real world coordinates. I'm not interested on streaming too. I want to use the map as offline also and basically edit(add structures, changing mesh and textures) in Unity if it is possible or in a 3d program like Maya f.e. and use the map for maybe simply create an alternative New York for a game or VR app like you can walk inside.

**Comment by GabrielBakker** [comment]
You can add objects in Unity pretty easily, and place them wherever you
want. I think there's a way to tell WRLD to not draw the buildings, so then
you would just use your own buildings.

Alternately there may be a way to change the textures that WRLD uses for
its buildings, to higher res textures. But if you want better building
shapes, you'll do that by adding your own objects.



By the way I should mention that I am not any kind of official and I don't
know any of the people who are .. i'm just a user like yourself. I made a
quick game using it a while ago, and found it pretty easy to get fairly
far, but then i hit a wall and couldn't get much farther, due to
performance issues with the plugin and a lack of configuration options for
streaming.


But its a really neat project.

I hope an official from the WRLD team answers your question soon. :)

Gabriel

**Comment by mehmetokalkan** [comment]
Waov then thank you to share your knowledge with me. I appreciate it. I just started use the asset and wonder about what is the potential and what we can do with it and end up here:) thanks again. Hope to hear soon from the offical team too.

Onur

**Comment by GabrielBakker** [comment]
Here's the game I ended up making for it, if you're interested :)

http://www.sageax.com/games/balloonride/

I'd love to see your project too if you want to share it sometime.

My game was made for the HTC Vive and works in Room scale VR, but there's
an option for playing in non-VR mode as well --- in Non-VR mode you want to
hold right click in order to look around, and use ASDW to move around.
(There's nothing preventing you from flying outside the balloon, because in
VR people's movement is prevented by the physical size of the room they're
playing in, so it wasn't necessary).

You can make the balloon rise by clicking on the lever to make the fire.
There's a rope you can pull to make it lower. And there are controls on the
balloon that you can use to visit different cities. You can change the time
of day and lighting effects by clicking on the clock.

Gabriel

**Comment by mehmetokalkan** [comment]
I had a project that tour bus in London but it is on the shelves now. Currently no project going on but I am making researches.
Your project idea is really nice and as a prototype its a cool game. But streaming works bad. LODs changing very often and I couldn't really enjoy the view:) And maybe balloon losing its altitude very quickly or maybe it is like that in real life, I never been in one of them. Good luck on your projects, if I will have a prototype like yours I love to share.

**Comment by GabrielBakker** [comment]
If balloon was losing altitude that's because of the temperature of the
air in your balloon compared to the elevation that the balloon is at.

Using the location selector to teleport to the mountains for example,
raises your elevation considerably, and that in turn reduces the outside
air pressure wire a bit and makes the balloon fall.

Keep in mind that the fire lever is not an "up button"and having the flames
on doesn't make the balloon go up.

Instead, having the flames on makes the balloon temperature go up and that
lowers the air pressure inside the balloon and once that is lower then the
air pressure outside, the lift force is applied.

Also with wrld the streaming gets better as time goes on because more of
the world is cached on your hard drive. Sometimes the first time you play
my game the balloon actually falls through the earth before the WRLD can
even stream anything!

And as you discovered, the LOD in WRLD has major problems for a project
like mine, and it's especially distracting in VR. This is ultimately why I
dropped the project.

Gabriel

**Comment by GabrielBakker** [comment]
Sorry, there was a typeo: I meant to say raising your elevation (especially
the sudden increase in elevation when you "teleport" to a mountainous area
like Denver or the Italian Alps), reduces the outside air pressure *"quite"*
a bit, which then makes the balloon fall.

You can read the details of the calculation on the display in the balloon.
The outside air pressure is determined based on the balloons elevation. The
inside air pressure is calculated based on the balloons temperature. The
lift or fall is calculated based on the difference between inside and
outside air pressures.

This ultimately resulted in a realistic movement that I really enjoyed, as
long as you're not expecting some dumb "arcade" style motion where fire
means up and no fire means slowly move down..

By using the actual physics formulas, you'll find that as the temperature
drops and the balloon falls, it will fall into pockets of thicker higher
density air and start rising again, even if the temperature goes down and
the fire remains off.

But keep your eye on that temperature. The temperature needs to reach
around 100c to be going up (or like 130c if you're in the mountains). Then
you'll find the descent is nice and slow.


But too bad there was nothing i could do about the LOD problems. Ultimately
I tabled the project until I have a chance to make my own terrain for
flying over.


Mostly it was a learning project anyway, just done for practice.


Gabriel

**Comment by mehmetokalkan** [comment]
I don't complain about mechanics, I am fan of simulations and appreciate your detaily calculations. I just shortly experienced your game. Also before anything I could do balloon felt to the ground.

It's a good project, keep going.

**Comment by GabrielBakker** [comment]
Right. Balloon starts on ground (or drops there immediately). You have to
pull the fire lever for 5 or 10 seconds to get into temperature range
before balloon can fly. :) Just trying to explain how the controls work.

Anyway thank you for trying it and for your feedback and encouragement :)

Gabriel

**Comment by lvl9lightspell** [comment]
I was looking to do the same thing. The solution I found is a little bit manual, but if you're looking to pre-generate your scene you're doing manual stuff anyway, so whatever.

In PreparedMesh::ToUnityMesh(), add the following line of code:
`UnityEditor.AssetDatabase.CreateAsset(unityMesh, "Assets/GeneratedMeshes/" + m_name + ".asset");`

This will save the meshes that Wrld generates to the GeneratedMeshes folder.

Point the WrldMap coordinates to the location you want and play the scene. Copy the items generated in the WrldMap hierarchy, then stop the scene. Paste the generated items back into your scene. Since the meshes are saved, the references to the meshes are persisted correctly.
