### ISSUE TITLE
How do I convert from lat/lon from unity coordinates and visa-versa, when using unity coordinate system?

### ISSUE THREAD

**Issue by tim-jenks** [wrld3d/unity-api#22]
question from @gmyv posted to wrld-example-app relayed here:

`What the title says. I need to know how to find a lat-lon place on the map, in unity coordinates and visa-versa. Thx.`

**Comment by tim-jenks** [comment]
Hi @gmyv, our latest SDK here should resolve the posititioning, issues for you, please see the Positioning examples here: https://docs.wrld3d.com/unity-SNAPSHOT/latest/docs/examples/position-object-at-latitude-and-longitude/

**Comment by gmyv** [comment]
How do I download that version of the SDK? When I import from the Unity Asset store, there is no Wrld/Demo/Examples.unity

Also, what is a coordinateFrame?

Can you please put more effort into the documentation to explain how things work? I can't make sense of that code example. It sets the box to a static position: Vector3(0.0f, 40.0f, 0.0f)

But that doesn't explain how it gets put in the correct Lat/Lon if its a hard-coded value, and also doesn't explain whatever a coordinateFrame is.

And I can't even open the "Examples.unity" because it doesn't exist in Asset store. Also, it says click the play button and select the dropdown... what dropdown?

Please make your documentation better.

**Comment by johnbell84** [comment]
Hi Gmyv,

Sorry for the confusion, it looks like we missed out a link.  You can access our latest snapshot builds at the link below.  Please note the snapshot build of our Unity SDK changes frequently and is less stable than the Unity Asset Store SDK.

https://eegeo-static.s3.amazonaws.com/unity/wrld.unity.sdk-SNAPSHOT.zip

That should contain the Examples.unity scene.  

When we talk about coordinate frames we’re referring to the origin and basis vectors of a coordinate system.  Together, they contain the information required to convert a coordinate value to or from the local space of that coordinate system.  A Unity GameObject’s transform property is an example of the concept.

I hope this helps.  Please let us know if you have any further problems.

Kind regards,

John

**Comment by tim-jenks** [comment]
This issue is now resolved and the feature available in the asset store version of our Unity SDK - closing.
