### ISSUE TITLE
Y Elevation in Unity World Coordinates

### ISSUE THREAD

**Issue by RPz376** [wrld3d/unity-api#3]
Per the Coordinate Systems explanation for  Unity World Space - "It centers a latitude and longitude at (0, 0) in Unity’s coordinate system and positions all meshes relative to that point **flat on the ground**." it would be expected that a map point with elevation 0 will be brought into the Unity scene with a y value of 0.  However, in every test I have made so far using Unity World Space, the y elevation for water surfaces (as well as terrain) appears to fall off on a spherical surface from the (0,0) center with the same 6,378,100 meter radius as the ECEF Space.   For example, in the default San Francisco location in Unity World Space, three sample water surface points were roughly measured in the sample Unity World Space scene as: (-17000 , -27.69 , 0), (-15000, -22.641, 0.0) and (-10500, -13.661, 0.0)  Is that intended?  I expected to see the water surface remain at a constant y elevation across the extent of the map in Unity World Space.  Or does **flat on the ground** mean the coordinate system remains flat but the geometry curves?

**Comment by johnbell84** [comment]
Hello,

Thanks for trying our maps!  This is really useful feedback.  It sounds like our explanation of the coordinate systems might need a little work.

The Unity World Space coordinate system essentially rotates the earth beneath you at startup.  From then on, the point at (Starting Latitude, Starting Longitude, 0.0) - expressed in lat/long and altitude from sea level - will correspond to (0,0,0) in Unity's X, Y and Z.  Unity's Y axis will point straight up through (Starting Latitude, Starting Longitude, 0.0).

The Earth is still spherical, but because it's so big the curvature only becomes apparent as you move further away from the origin (we'd recommend staying within ~25km, but this might vary depending on what exactly you're doing).  You're correct that you will be able to observe this as the sea sloping away from the starting lat/long if you go far enough.  The starting latitude and longitude can be edited to base the map around any central location you require.

If you need to work continuously on a global scale, we'd recommend using our ECEF coordinate system instead.  Working at a global scale can stretch the abilities of Unity's default 32-bit floating point numbers, so this mode continuously re-positions resources relative to the camera to help maintain the precision needed for good visual fidelity.  It is described in further detail here:

    https://wrld3d.com/unity/latest/docs/examples/ecef-coordinate-system/

Thanks again for the feedback, we'll try to make the documentation clearer in future.

John
