### ISSUE TITLE
Scene shaking when travelling long distances

### ISSUE THREAD

**Issue by amitchai** [wrld3d/unity-api#42]
Hello,
This may be unity issue because I've already checked a few forum discussing this issue, their suggestion was to transfer the entire scene objects to the opposite screen bar when traveling more than 8km. I think this method is impossible with your asset because objects are locked. So this is causing a big issue because everything is shacking. I think maybe there is no choice but to create save points at the far edge. now is there a way to transfer the player position after traveling big distance, into a new set of points. This may cause more problems, but I don't know if there is a solution to this. Plase, help!

**Comment by malcolm-brown** [comment]
Believe this issue is loosely explained in our [Coordinate Systems](https://wrld3d.com/unity/latest/docs/types/Wrld.CoordinateSystem/) documentation.

The short of it is, Unity struggles with large values for positions due to floating-point precision.  There are two ways around this when using the WRLD Unity API:

**Using Unity World Space & [API.SetOriginPoint()](https://wrld3d.com/unity/latest/docs/types/Wrld.Api/)**

When using Unity World Space, the position you provide for the starting latitude and longitude is used as the Origin Point of the scene, aka a gameobject with a position of 0,0,0 will appear over this latitude and longitude.  The further away and object is from this origin, the more problems you'll run into with precision issues.  To solve this, you can update the origin point by calling Api.SetOriginPoint.   

When calling this, both the built-in camera or objects using [GeographicTransforms](https://wrld3d.com/unity/latest/docs/examples/position-object-at-latitude-and-longitude/) will be automatically re-positioned to account for this, but objects that don't use these will appear to move unless they are updated.    You can recalculate their correct position via the [GeographicToWorldPoint](https://wrld3d.com/unity/latest/docs/types/Wrld.MapCamera.CameraApi/) method.

In general, you'll want to keep objects relatively (8km as mentioned) close to the Origin Point.  If objects start to get too far away, then you need to consider updating the Origin Point to somewhere closer.


**ECEF World Space**

The ECEF World space works a little differently, in that the world is constantly repositioned around the camera's position, meaning that the camera always represents the origin (0,0,0) in the Unity scene.  This means you should never encounter the precision issues mentioned, but the ECEF space is a little harder to work with due to it representing the world as a sphere.  For more information on the ECEF coordinate system, [refer to this documentation](https://wrld3d.com/unity/latest/docs/examples/ecef-coordinate-system/).

I'd recommend trying to update the Origin Point in Unity World Space and see if this fixes your issue.

**Comment by amitchai** [comment]
Thanks! I am going to check this.

**Comment by tim-jenks** [comment]
Closing as this should be resolved. Please reopen if you have further discussion.
