### ISSUE TITLE
GeographicTransform.SetPosition not working properly

### ISSUE THREAD

**Issue by silentsword123** [wrld3d/unity-api#46]
When I tried to use GeographicTransform.SetPosition to place an object on the map based on its LatLong, it looks like there will be a pretty big error comparing to the real life. Does anyone know how to solve this problem? Thanks!

**Comment by jlunderwood** [comment]
Without knowing more detail, it sounds like you may be encountering problems due to floating point precision in Unity. See the discussion at [https://github.com/wrld3d/unity-api/issues/42#issuecomment-340405688](https://github.com/wrld3d/unity-api/issues/42#issuecomment-340405688,) which contains links to documentation and some suggestions for how to minimize the errors.

If you are still having problems, please let us know of a specific latitude/longitude and Origin Point combination which demonstrate the issue.

**Comment by silentsword123** [comment]
Hello. The Origin Point is Central Park which is 40.7829° N, 73.9654° W. And I tried to put an object on the top of the metropolitan museum of art which is 40.7794° N, 73.9632° W. From my understanding, they are very close to each other, there shouldn't be the problem of floating point precision in Unity. Thanks!

**Comment by jlunderwood** [comment]
I'm attaching a screenshot of the RotateObjectOnMap example which comes with the asset. I've changed the start latitude/longitude to 40.7829, -73.9654, and  the cube location in RotateObjectOnMap.cs to be `static LatLong startPosition = LatLong.FromDegrees(40.7794, -73.9632);` This example then calls GeographicTransform.SetPosition to position the cube.  As the start point is not at the cube location, you do need to pan the map so that the Metropolitan Museum of Art is in the view, but the cube seems accurately positioned.

Can you tell me what you're seeing that's different?
![mma nyc panned](https://user-images.githubusercontent.com/19375948/32557650-a70e6b14-c49a-11e7-8c67-8b8153e438b6.png)

**Comment by silentsword123** [comment]
Thanks for the replying! Is that means when we want to call SetPosition, the target location needs to be in the camera view? And below is the screenshot how it works on our project. 
![image](https://user-images.githubusercontent.com/24457128/32575461-193d26c4-c4a2-11e7-85a2-2aaa504aac9c.png)

**Comment by jlunderwood** [comment]
SetPosition does not require the target location to be in the camera view.

From your screenshot, it looks like you are looking at the scene view.  SetPosition is designed to keep the object with the GeographicTransform component synchronized with the map position in play mode.  Are you seeing an offset when the scene is run?

**Comment by silentsword123** [comment]
Yes, I do see an offset when the scene is run. The object was at the same location in both scene view and play mode.

**Comment by jlunderwood** [comment]
Can you check that your object is a child of the GeographicTransform?  How have you set the position -- using the inspector or in code? Have you registered the GeographicTransform using Api.Instance.GeographicApi.RegisterGeographicTransform?

**Comment by silentsword123** [comment]
Finally it works. Great thanks!

**Comment by silentsword123** [comment]
Just got one question. Does it matter if we use a separate camera to stream map?
