### ISSUE TITLE
Idea: Accelerated visual and physics mesh generation

### ISSUE THREAD

**Issue by AubreyF** [wrld3d/unity-api#50]
Greetings WRLD team! I'm working on a prototype vehicle combat/exploration simulator, and will be experimentally integrating your streaming terrain library over the next few weeks to assess it's potential applications in a fast-paced first-person experience.

I have been experimenting with the StreamResourcesForCamera system, and would like to suggest a few improvements. I am also quite interested in hearing from you on best practices for implementing the current production API.

1) Visual mesh generation.
Right now, the frustum culling system used for visual mesh generation instantly destroys meshes which are outside the field of view. This is a problem, because it currently takes many update frames to rebuild visual meshes once they are back in view. This means that whenever a camera is rotating, city elements will pop in and out of view even in a best-case scenario where the local area has already been fully explored and locally cached. Instead of the current frustum approach, a simple proximity system coupled with Unity's automatic frustum culling would provide a seamless view of the local environment. I am currently experimenting with a non-rendering camera which points down from above the player's camera to force proximity-driven WRLD streaming, but this approach doesn't allow for full expression of the tileset LOD system. Are you potentially interested in offering an alternative streaming mode that would be optimized for first-person experiences in which the viewer's camera is often rotated?

2) Physics mesh generation
The simulator I am building includes both rapidly moving vehicles and projectile weapons. This means it needs all the Terrain, Road, and Building collision geometry for streamed cities. Unfortunately, my game's framerate drops to single digits on even a powerful gaming machine when I have a camera rotating in the middle of a city with all WRLD collision geometry enabled. I am planning to experiment with multiple WRLD instances present in a scene simultaneously. All instances would have their own non-rendering overhead cameras, each positioned to provide a specific surrounding proximity distance from the player's camera. The visual WRLD instance would have a large proximity distance. The terrain-collision instance would have a medium proximity distance, and the road/building collision instance would have a small proximity distance. Does this approach seem feasible, and/or do you have any alternative ideas?

**Comment by tim-jenks** [comment]
Hi @AubreyF 

Totally agree with you on your points. Some thoughts:

1. Our underlying streaming volume can actually be any volume, it doesn't have to be the camera frustum. The streaming and render volumes are currently decoupled, it should totally be possible to specify another volume for streaming, i.e. you could position a camera 'top down' looking down at the player, and use that as the streaming volume - some very hinty notes are at the bottom of this page: https://docs.wrld3d.com/unity/latest/docs/examples/using-your-own-camera-controls/ - but we'll probably get a better example out of how to do this.

2. We currently have two modes of LOD selection, distance based, or fixed by altitude. This is an area we're looking to expand upon, and also provide additional higher-level API access to the mechanisms of LOD selection. Can't give you any dates unfortunately

3. Physics volumes are a little bit of a problem for us in Unity, our underlying C++ SDK doesn't make use of separate physics volumes to keep streamed data as small as possible, rather we have a bounding view hierarchy to accelerate are already relatively simple render meshes for the purposes of fast(er) physics queries. Unfortunately this isn't how Unity's physics works, at the moment we're naively, and optionally, throwing the render meshes at Unity to generate physics hulls, which is dire and slow. We'll likely have to look again in a future release of the Unity SDK to address this.

Hope this adds some clarity - again marking as question and keeping this open for future comment.

**Comment by AubreyF** [comment]
@tim-jenks 

1. I am seeing great (visual mesh performance) results experimenting with the floating camera approach. It still feels suboptimal from an accurate lod-distance assessment perspective, but has already been performant enough in testing to provide an incredibly enjoyable flight simulator experience for cities all over the world.

2&3, Collision mesh generation performance is now the only showstopping issue with the first-person city exploration experience I am building. My initial idea of multiple WRLD SDK instances responsible for visual and collision meshes respectively hasn't yet panned out. The API's singleton instance pattern seems to discourage this. It would be fantastic if a future SDK release could automatically generate simple bounding boxes for mid-distance objects, ignore physics generation for far objects, and generate high-detail collision meshes only for near objects. Short of this, a conflig flag to generate physics objects only within a configurable proximity of the main camera and ignore camera frustum culling would still be solid win. Question: Should I be able to run two simultaneous WRLD API instances for now, or are they most likely going to fight over cache race conditions/instance references/etc? Also, is there a performant way to disable visual mesh generation for the physics-managing instance in the currently released SDK version?

**Comment by ghost** [comment]
Running two WRLD Instances in the same Unity project is not supported, not is it possible to disable the visual mesh generation.
