### ISSUE TITLE
Skybox in ECEF coordinate system

### ISSUE THREAD

**Issue by silentsword123** [wrld3d/unity-api#55]
When using ECEF coordinate system, the unity skybox doesn't work well with it. It looks like this
![image](https://user-images.githubusercontent.com/24457128/33330087-ec0ada04-d42b-11e7-8be6-6125c0be45a7.png) Does anybody know how to make the skybox work well with the ecef system? Thanks!

**Comment by malcolm-brown** [comment]
Unity's procedural skybox material shown above seems to work on the basis on the y-axis representing 'up'.  This is what the "Unity World" world space does in order to provide compatibility with common Unity use cases such as this.

The "ECEF" world space however, represents the world as a sphere (see https://docs.wrld3d.com/unity/latest/docs/examples/ecef-coordinate-system/ for more info).  This isn't compatible with a lot of Unity systems that expect the y-axis to represent 'up' (see also Unity's physics, although you can change the Gravity vector to accommodate this).  As such, if you want to use other Unity features with the Wrld API, we'd recommend using the Unity World space.

If you still wish to use the ECEF world space, you'll likely need to either modify Unity's shader to provide some way of rotating the generated skybox, or use a different method of rendering a skybox that lets you reorientate it with the surface of the world - https://docs.wrld3d.com/unity/latest/docs/types/Wrld.Common.Maths.EcefTangentBasis/ may help here.

**Comment by tim-jenks** [comment]
Closing this issue as the comment from @malcolm-brown explains how to add an ECEF oriented custom skybox. If this is insufficient, please re-open.
