### ISSUE TITLE
Change template graphics or material settings for raster terrain

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#59]
Is there a way to change the materials or template graphic setting when you zoom out and see the earth terrain?

**Comment by tim-jenks** [comment]
@yosun this is not currently possible unfortunately, I have added as a future enhancement

**Comment by yosun** [comment]
Is there a way to limit how far the user can zoom out?

**Comment by johnbell84** [comment]
Hi yosun,

I'm afraid there isn't currently a way to do this with our built-in camera controller, but if you like you can control the camera yourself by unchecking "Use Built-in Camera Controls" on your Wrld Map instance in the Unity Inspector.  You should then be able to drive the camera with your own code and enforce any limitations.

It would probably be easiest to do this with your World Space set to "Unity World", as this orients the resources so that the up direction points along Unity's positive Y-axis, which is likely to be a more intuitive space to work in.

I hope this helps.

Kind regards,

John

**Comment by jonty-dawson** [comment]
For original question, no current plans to allow override of display of streamed satellite imagery when viewed at high altitude.
