### ISSUE TITLE
WebGL Support Unity plugin

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#60]
I notice WebGL is not officially supported yet... though it remains one of the most versatile ways to share Unity apps 

Is WebGL support on the roadmap for the Unity plugin?

**Comment by johnbell84** [comment]
Hi yosun,

Thanks for your interest in our maps!

You can can deploy for WebGL via our javascript SDK.  The api documentation and examples are available here:

	https://www.wrld3d.com/wrld.js/latest/docs/api/
	https://www.wrld3d.com/wrld.js/latest/docs/examples/

At the moment we’re not actively working on support for WebGL deployment via Unity, but we do try to drive our development according to developer demand, so this could be something we focus on if it becomes a popular request.

I hope this helps.

Kind regards,

John

**Comment by yosun** [comment]
I believe WebGL Unity support is just cross compiling your source with emscripten asm.js 
Unity WebGL is the easiest way to show Unity  apps/games - without requiring pesky downloads.  

This should be a lot easier than you'd expect, so do consider it as a small but impactful project for the roadmap!

**Comment by tim-jenks** [comment]
This is tentatively on our roadmap, but I doubt for 2018. In the mean time we're encouraging use of wrld.js for JS deployments.

As a bit of background here: WRLD at it's core is a C++ SDK, our Unity SDK loads a pre-built native library. Unity cannot do the conversion to asm.js for us, as we don't provide LLVM or IL to Unity for the core WRLD SDK.

However, this is possible, as our core C++ SDK is already cross-compiled to asm.js using emscripten for wrld.js, it is a somewhat non-trivial amount of work for us to support the JS deployment target on Unity, user + customer demand will drive our adoption of this. 

I will reopen + mark this as an enhancement and anyone else requiring this can upvote.

**Comment by JoelPlourde2** [comment]
Hi !

I am also interested in the support of the WebGL Platform. Actually, I was pretty surprised that it is not pfficially supported yet. However, by reading your comments, I understand the non-trivial amount of work.

I agree with Yosun, it is a small but impactful project enhancement for the project as a whole.

**Comment by jacquesleemans** [comment]
Hi, any update on the support for WebGL?

**Comment by jonty-dawson** [comment]
Targeting of WebGL for WRLD Unity SDK is not currently on our roadmap. As mentioned above, we target WebGL via our javascript SDK - WRLD.js. This is our recommended approach for using WRLD maps and services via web browsers.
See https://wrld3d.com/wrld.js/latest/docs/api/

**Comment by ZohraS** [comment]
Hi, is it ever going to be on the roadmap? I desperately need the webgl to work directly out of unity, not via js. I'd really just like a status update on this, to know if it's even something I have to expect in the future or not. Thanks!

**Comment by jonty-dawson** [comment]
Hi ZohraS - unfortunately there is no change here, the targeting of WebGL for WRLD Unity SDK is not on our roadmap. It's possible that this may change in the future, as we understand that this is a feature that some developers are requesting, but it does not feature in our current planning.

**Comment by more869** [comment]
Hi, I would also take part in this discussion.
I work for a large consulting and engineering company that has been using Unity technology for many years. We have been seeing a constant rise in demand for WebGl applications. With the rise of different mobile technology and HTML5 we can see exponentially increased demand for a browser running technology that is universal regardless of platform. New business development apart from gaming and entertainment is emerging very rapidly as civil engineering and even military contracting is adopting the use of game engines in their productivity.

Currently our company is arriving at a crossroads with regards continuing using Unity because of the lack of proper future support for WebGl which is the preferred platform for us to share our unity created products with our clients. We are forced to look alternatives at this point. I hope at Unity the future growth of WebGl or similar technology are being closely followed and recognized in the management level.

It seems a bit short sighted as a strategy not to plan more support for WebGl at the moment. Perhaps people are not vocal about it and do not let Unity know of their increased need for it, but instead adopt other solutions in a quiet manner.

Unity has been a wonderful development platform for us and we are still optimistic about using it in the future. However currently we need to focus on alternatives untill WebGl receives more love in a Unity roadmap. By this I am trying to give acknowledgement for the need of more WebGl support. We have more browser support coming and webassembly taking more ground with also better memory management for WebGl uses. Unless something replaces the need for WebGl development, we can see it continue to grow.

I appreciate you guys giving us in depth look into how it's looking currently, just wish there was more news on that front. Keep up the good work! 😃

**Comment by ghost** [comment]
Sorry, still no plans to support WebGL deployment of WRLD Unity apps.
