### ISSUE TITLE
How to do terrain loading no matter where the camera looks?

### ISSUE THREAD

**Issue by batomot** [wrld3d/unity-api#70]
Hello, I'm not a programmer, but how to make the loading area (LOD) that does not depend on where the camera looks ? 
Well, I mean that the area was uniformly absorbed regardless of where the camera looks like chunks around the camera. 
If you can do that, how ?

**Comment by johnbell84** [comment]
Hi Batomot,

Due to memory and performance concerns, the SDK only loads visible areas into memory.  The SDK considers an area "visible" if it intersects with the camera supplied to the SDK.  In Unity, you can use one camera for rendering and a different camera for loading WRLD resources.  This will allow you to have greater control of the streamed and memory resident data.

There is documentation for this here https://wrld3d.com/unity/latest/docs/examples/using-your-own-camera-controls/, and discussions at https://github.com/wrld3d/unity-api/issues/7 and https://github.com/wrld3d/unity-api/issues/44.   You may also be able to adapt the "Separate Streaming and Rendering" example in the Wrld/Demo/Examples.unity scene.

I hope this helps.

Kind regards,

John
