### ISSUE TITLE
Trying to get Dubai map in my Unity scene but can not. 

### ISSUE THREAD

**Issue by Vinita18** [wrld3d/unity-api#75]
I am adding latitude and longitude details in WRLD map inspector window but nothing happens. Is there any other way to do it?

**Comment by kyle-welsh** [comment]
Hi  Vinita18, 

Unfortunately our Dubai data is currently only available privately due to a commercial agreement involving private data. 

If you would like to vote for Dubai to be built using public data, and therefore added to our public maps, you can vote for it here 
https://www.wrld3d.com/3d-maps/mapping-data#WRLD-MAP-COVERAGE

We take the data gathered here from customer demand into account when deciding which area of the world we'll build next, with the eventual goal being full-world coverage. 

If you would like to discuss a commercial agreement of your own to expedite the building of Dubai, please email enquiries@wrld3d.com to speak to our sales team.  

Regards, 
Kyle
